apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240110035224.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240110035224.0.0+build.02e9424
  releaseNotes: |
    Release v20240110035224.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-22-42-29-098662423/where-for-dinner-search-my-apps-bundle@sha256:eee1ded7e904f36d60435b38323dd498e6f468af8a02fea13642ac1918565ebd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

