apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240110035145.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240110035145.0.0+build.02e9424
  releaseNotes: |
    Release v20240110035145.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-22-42-29-098662423/where-for-dinner-my-apps-bundle@sha256:3dd9edad77cc2e23d7622bd5f3f362e0680cd1d8437c369e764c1bf035b00d35
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

